### PR TITLE
fix issue #105 (Error when using puppet apply (the serverversion fact is not present))

### PR DESCRIPTION
**Pull request by empi89**
see comment below

### CODE REVIEW

**Comment by ferventcoder** [comment]
@empi89 would you mind taking a look at the contributing document over at https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#prepare-commits (the prepare commits section) and emulate that for your commit message here? Thanks in advance!

**Comment by empi89** [comment]
I have now changed my commit message and also changed the logic to "and" again.

**Comment by ferventcoder** [comment]
Waiting for appveyor now.

**Comment by empi89** [comment]
appveyor done :+1:

**Comment by ferventcoder** [comment]
Thanks!

**Pull request merged**
