### PR TITLE
added parameter $ignore_proxy

### LINKED ISSUE #143: InstallChocolatey.ps1 doest look at system proxy-bypasslist when downloading choco from url
choco should look at netsh winhttp show proxy

### PR DESCRIPTION
**Pull request by maxgaulhofer**
Closes #143

### CODE REVIEW

**Comment by maxgaulhofer** [comment]
I already created an issue earlier today https://github.com/chocolatey/puppet-chocolatey/issues/143 Let me know if i should update this with more information. I also squashed the commit :-)
Is there a reason why the rspec test are failing?
Thanks for your comments and hard work

**Comment by ferventcoder** [comment]
Yes and not your fault. We need to add something to the gemfile to keep json_pure working.

**Comment by ferventcoder** [comment]
For the commit changes, I'm looking for `(GH-143) short message total 50 chars`, an empty line, and then a message explaining the changes and why they are necessary. This is a good explanation of what is requested - https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#prepare-commits

**Comment by maxgaulhofer** [comment]
ok changed the commit message

**Comment by ferventcoder** [comment]
Also added similar to https://github.com/chocolatey/chocolatey.org/issues/433 - https://chocolatey.org/install.ps1

**Pull request merged**
