### PR TITLE
Fix tests chocolatey download url

### PR DESCRIPTION
**Pull request by empi89**
See issue #111.

### CODE REVIEW

**Comment by empi89** [comment]
You need to integrate #109 first.

**Comment by ferventcoder** [comment]
Like it.

**Comment by stefandollase** [comment]
:+1:

**Comment by ferventcoder** [comment]
Restarted TravisCI.

**Comment by ferventcoder** [comment]
Well it passed in 2.1.5 - failed in the others - https://travis-ci.org/chocolatey/puppet-chocolatey/builds/97406614

**Comment by ferventcoder** [comment]
Or I should say, passed in Puppet v4+.

**Comment by ferventcoder** [comment]
It's likely that both false and 3 are treated as strings in Puppet v3.

**Comment by ferventcoder** [comment]
@empi89 have a look at https://github.com/chocolatey/puppet-chocolatey/blob/9219ee0dfe36084249a4e0f2309ef52b46862110/spec/classes/init_spec.rb#L68-L121 for a hint on how you will need to fix this.

**Comment by empi89** [comment]
I have just rebased this commit to current master. I will check your suggestion tomorrow.

**Comment by empi89** [comment]
works with puppet 3 now :-) :+1:

**Comment by ferventcoder** [comment]
Interesting way about it, like it!

**Pull request merged**
