### PR TITLE
fix documentation on choco_install_timeout

### PR DESCRIPTION
**Pull request by empi89**
choco_install_timeout was replaced by choco_install_timeout_seconds

### CODE REVIEW

**Comment by ferventcoder** [comment]
Thanks! I see there may be an issue with travis-ci but I haven't had a chance to look into it yet.

**Comment by ferventcoder** [comment]
The error looks unrelated.

**Comment by empi89** [comment]
yep, this PR is only fixing documentation and should not change functionality.

**Comment by ferventcoder** [comment]
Thanks again!

**Pull request merged**
